name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10, 12]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install, build and test
        run: |
          yarn install
          yarn lint
          yarn build
          yarn test:cov
          bash <(curl -s https://codecov.io/bash)
